Back 5 sequelize
yanprak/yan-run pull request #54
Opened 2021-03-30 21:04 UTC by rade363

2021-03-31 10:42 UTC, chidori requested changes
По всем файлам надо обсудать `user_id` vs `userId`. И про внешние ключи соответственно тоже (коммент из User.ts)

2021-03-31 10:42 UTC, chidori commented on src/server/api/models/Theme.ts
> +  style: string;
Здесь бы надобно тоже Record, непонятно как там дальше это будет при непосредственной работе с моделями резолвится
```suggestion
  style: Record<string, unknown>;
```

2021-03-31 10:42 UTC, chidori commented on src/server/api/models/User.ts
> +  theme!: number;
@Column field: 'id', это типа так указывается поле для foreign key? просто чет в доке такого не нашел. И не сильно очевидно выглядит.

Логичнее и правильнее назвать поле themeId и сделать
```suggestion
  @ForeignKey(() => Theme)
  @AllowNull(false)
  @Column(DataType.INTEGER)
  @Default(1)
  themeId!: number;
```

А еще очень похоже, что DataType.INTEGER можно не писать для number полей - он типа сам умеет вычленять.

2021-03-31 10:42 UTC, chidori commented on src/server/api/models/Topic.ts
> +  messages_count: number;
Сижу и думаю насколько это поле нужно, когда его через JOIN посчитать можно.
Просто обновлять каджый раз - это нормально, и даже с точки зрения денормализации, но вот прикол в том что обновляться будет через UPDATE - и может получится так (теоретически), что было 5 сообщений добавилось два и оба сделали 5+1(себя типа добавили) и получили на выходе 6 вместо нужных 7ми.

Обсуждаемо

2021-03-31 10:42 UTC, chidori commented on src/server/api/models/Topic.ts
> +  user_id!: number;
Описывал это в User.ts
И теперь вопрос в javascript нам надо иметь userId, в базе user_id, и надо как-то этого добиться
или же договорится о допущении этого, потому как все таки snake_case - это не про javascript

2021-03-31 10:42 UTC, chidori commented on src/server/api/models/Message.ts
> +  replies!: Message[];
Это поле не нужно так как пользы оно никакой не принесет, а менеджить будет тяжко.
Единственная польза - рекурсивное хранение ответов, но так ли оно нужно?

2021-03-31 10:42 UTC, chidori commented on src/server/api/models/Message.ts
> +  @BelongsTo(() => Reaction)
а разве тут не \@HasMany должно быть?

2021-03-31 10:42 UTC, chidori commented on src/server/api/models/Reaction.ts
> +  name: string;
А почему здесь тип не enum тогда?
Опять же в базе используешь стринг а не enum-тип, давай оно просто строкой будет перечесляемой.
type Reaction = 'like' | 'dislike' ...
Единственным числом если что )

2021-03-31 10:42 UTC, chidori commented on src/server/api/models/Reaction.ts
> +class Reaction extends Model<ReactionAttributes> {
множественное число
```suggestion
class Reactions extends Model<ReactionAttributes> {
```

2021-03-31 11:11 UTC, rade363 commented on src/server/api/models/User.ts
> +  theme!: number;
Круто! Не знал что сам умеет. Тогда удалю лишние указания `DataType` для `INTEGER` колонок.

А по поводу 
```
@Column({
  ...,
  field: id
})
```

делал по примеру в теории ([связи](https://praktikum.yandex.ru/learn/middle-frontend/courses/ce1c09fb-f189-4b3d-9662-9dde4d271257/sprints/5151/topics/1eb16d47-5fe3-4b2a-b2ce-e8f1a905d897/lessons/27beb206-bcbf-493e-8591-dbaae2a9f39b/)):
```
class Message extends Model<Message> {
    @ForeignKey(() => User)
    @Column({
        type: DataType.INTEGER,
        field: 'owner_id'
    })
    ownerId: number;
}
```

2021-03-31 11:16 UTC, rade363 commented on src/server/api/models/Topic.ts
> +  user_id!: number;
Согласен про snake_case, он всё-таки по PHP и Python, а не по JS.

В данной задаче использовал его тупо по примеру того, что нам было предоставленоо в Swagger'е - там всюду `user_id`. Решил оставить этот некрасивый подход для consistency.

2021-03-31 11:24 UTC, rade363 commented on src/server/api/models/Message.ts
> +  replies!: Message[];
Да, действительно, `parent_id`/`parentId` по идее достаточно, это лишнее. Привык к GraphQL, my bad.

2021-04-02 05:34 UTC, ferahar approved these changes

2021-04-02 11:56 UTC, antonkagakin requested changes

2021-04-02 11:56 UTC, antonkagakin commented on src/server/api/models/Message.ts
> +class Message extends Model<MessageAttributes> {
Messages
надо проверить все таблицы на множественное число

2021-04-02 11:56 UTC, antonkagakin commented on src/server/api/models/Message.ts
> +  userId!: number;
здесь таки надо указывать `field: 'user_id'`, чтобы в базу они все таки в snake_case попали, ну и со всеми case'ами так просмотреть чтобы было

2021-04-02 11:56 UTC, antonkagakin commented on src/server/api/models/Theme.ts
> +class Theme extends Model<ThemeAttributes> {
Также про множественное

2021-04-02 11:56 UTC, antonkagakin commented on src/server/api/models/Topic.ts
> +class Topic extends Model<TopicAttributes> {
Всё еще множественное )

2021-04-02 11:56 UTC, antonkagakin commented on src/server/api/models/Topic.ts
> +  messagesCount!: number;
`field: 'messages_count'`, чтобы в базе snake_case был

2021-04-02 11:56 UTC, antonkagakin commented on src/server/api/models/User.ts
> +  @Column(DataType.INTEGER)
`field: 'theme_id'`

2021-04-02 22:50 UTC, rade363 commented on src/server/api/models/Message.ts
> +class Message extends Model<MessageAttributes> {
Хм, странно, в примерах в теории - единственное число:
```
class Message extends Model<Message> {
    @ForeignKey(() => User)
    @Column({
        type: DataType.INTEGER,
        field: 'owner_id'
    })
    ownerId: number;
}
```

Да и в [документации](https://www.npmjs.com/package/sequelize-typescript) тоже.

2021-04-03 07:11 UTC, antonkagakin requested changes
Илья, у нас таблицы users, messages, topics - множественные числа
потому `class Users` `class Messages` `class Topics` `class Themes`, а они у нас сейчас в единственном числе получаются

2021-04-03 12:01 UTC, antonkagakin requested changes

2021-04-03 12:01 UTC, antonkagakin commented on src/server/api/models/Messages.ts
> +  @Column(DataType.INTEGER)
```suggestion
  @Column({
    type: DataType.INTEGER,
    field: 'parent_id'
  })
```
Пройдись, пожалуйста, по всем полям во всех таблицах чтобы было соответствие camelCase -> snake_case для JS -> DB

2021-04-03 13:33 UTC, rade363 commented on src/server/api/models/Messages.ts
> +  @Column(DataType.INTEGER)
Но я же уже прошёлся в коммитах выше. В JS свойства сделал camelCase, в вот этих вот объектах - snake_case. Тут единственное место где пропустил.

2021-04-04 14:11 UTC, antonkagakin requested changes

2021-04-04 14:11 UTC, antonkagakin commented on src/server/api/models/Messages.ts
> +  @Column(DataType.DATE)
field: created_at

2021-04-04 14:11 UTC, antonkagakin commented on src/server/api/models/Topics.ts
> +  @Column(DataType.DATE)
field: created_at

2021-04-04 14:11 UTC, antonkagakin commented on src/server/api/models/Users.ts
> +  @Column(DataType.STRING)
field: first_name

2021-04-04 14:11 UTC, antonkagakin commented on src/server/api/models/Users.ts
> +  @Column(DataType.STRING)
field: second_name

2021-04-04 14:11 UTC, antonkagakin commented on src/server/api/models/Users.ts
> +  @Column(DataType.STRING)
field: display_name

2021-04-04 14:11 UTC, antonkagakin commented on src/server/api/models/Users.ts
> +  theme!: number;
themeId!: number;

2021-04-05 12:05 UTC, antonkagakin approved these changes

2021-04-05 12:54 UTC, merged