Front 44 themes
yanprak/yan-run pull request #55
Opened 2021-04-01 14:38 UTC by ferahar

Ревью принимается)) Сливать не нужно, так необходимо прописать работу с API(ручки)

2021-04-01 23:14 UTC, rade363 reviewed
На мой взгляд всё круто с точки зрения логики, но есть несколько минорных моментов связанных с неймингом/названиями функций, thunk'ов - можно обсудить

2021-04-01 23:14 UTC, rade363 commented on src/client/store/theme/types.ts
> +  type: 'SET_THEME_CUR';
Тоже минорная околовкусовщина - может не сокращать CURRENT до CUR? И порядок слов поменять на `SetCurrentThemeAction`.

2021-04-01 23:14 UTC, rade363 commented on src/client/utils/themeChange/index.ts
> +  });
Минорное:
```
Object.entries(data).forEach(([key, value]) => {
    root.style.setProperty(key, value);
});
```

2021-04-01 23:14 UTC, rade363 commented on src/client/utils/themeChange/themes/index.ts
> +import ligth from './light';
Опечатка)
`ligth` -> `light`

2021-04-01 23:14 UTC, rade363 commented on src/client/store/theme/thunks.ts
> +const thunkThemeCur = <T>(data:T) => (dispatch: Dispatch) => {
Соответственно тут тоже `thunkGetCurrentTheme`

2021-04-01 23:14 UTC, rade363 commented on src/client/store/theme/thunks.ts
> +const thunkThemes = <T>(data:T) => (dispatch: Dispatch) => {
Тоже минорный момент.
Не нашёл, где используется, поэтому и показалось слегка неочевидным название. 
Этот thunk является ответственным за сбор доступных тем юзеру?
Может тогда обозвать `thunkGetThemes` или `thunkListThemes`?

2021-04-01 23:14 UTC, rade363 commented on src/client/store/theme/types.ts
> +  name:string,
Пробел убежал 😅

2021-04-01 23:14 UTC, rade363 commented on src/client/utils/themeChange/themes/light.ts
> +export default ligth;
Воу, целая новая тема) Интересно 👍👍

И `ligth` -> `light`

2021-04-02 12:29 UTC, antonkagakin requested changes

2021-04-02 12:29 UTC, antonkagakin commented on src/client/components/app/App.tsx
> +    themeChange(theme.current);
давай changeTheme 😄

2021-04-02 12:29 UTC, antonkagakin commented on src/client/hooks/useTheme/index.ts
> +      const num = current.id === 0 ? 1 : 0;
Раз уж мы решили, что темы будет 2, то давай обзовём функцию toggleTheme, вместо handleTheme ))

2021-04-02 12:29 UTC, antonkagakin commented on src/client/store/theme/actions.ts
> +export const setThemeCur: ActionCreator<ThemeAction> = (current: UserTheme) => {
```suggestion
export const setCurrentTheme: ActionCreator<ThemeAction> = (current: UserTheme) => {
```

2021-04-02 12:29 UTC, antonkagakin commented on src/client/store/theme/thunks.ts
> +const thunkThemeCur = <T>(data:T) => (dispatch: Dispatch) => {
это thunkSetCurrentTheme :)

2021-04-02 12:29 UTC, antonkagakin commented on src/client/store/theme/thunks.ts
> +const thunkThemes = <T>(data:T) => (dispatch: Dispatch) => {
thunkSetThemes видимо

2021-04-02 12:29 UTC, antonkagakin commented on src/client/store/user/thunks.ts
> +    .then(() => getTheme(1))
Нет апи - нет проблем XD

2021-04-02 12:29 UTC, antonkagakin commented on src/client/utils/themeChange/index.ts
> +export default function themeChange(theme:UserTheme = light) {
Присоединяюсь

2021-04-02 12:29 UTC, antonkagakin commented on src/client/utils/themeChange/index.ts
> +  });
Нууу )) в случае entries ты создаешь массив массивов )) в случае keys - только один массив строк )) Так что это на любителя и вкусовщина )
Да и дестракчеринг лишний раз не делаешь

2021-04-02 12:29 UTC, antonkagakin commented on src/client/utils/themeChange/type.ts
> +};
Как альтернативная запись - `export type Theme = Record<string, string>`

2021-04-02 12:29 UTC, antonkagakin commented on src/client/store/user/thunks.ts
> +      dispatch(setThemeCur(theme));
setCurrentTheme

2021-04-03 07:22 UTC, antonkagakin requested changes
Класс :)
Немного множественного числа в именованиях и гуд )

2021-04-03 07:22 UTC, antonkagakin commented on src/client/API/theme.ts
> +const getAllTheme = () => themes;
```suggestion
const getAllThemes = () => themes;
```
)))

2021-04-03 07:22 UTC, antonkagakin commented on src/client/css/common.scss
> +  }
чет статью вроде читал, что outline нельзя отключать :) и там даже весомые аргументы приводились
на подобии этой: http://www.outlinenone.com/
Это для accessibility типа супер-важно, не то чтобы мы претендуем на фул-саппорт для всего-всего, так для развития )

2021-04-03 07:22 UTC, antonkagakin commented on src/client/store/theme/actions.ts
>  export const SET_THEME = 'SET_THEME';
```suggestion
export const SET_THEMES = 'SET_THEMES';
```

2021-04-03 07:22 UTC, antonkagakin commented on src/client/store/theme/types.ts
>    type: 'SET_THEME';
```suggestion
  type: 'SET_THEMES';
```

2021-04-03 07:22 UTC, antonkagakin commented on src/client/store/theme/types.ts
>  export interface SetThemeAction extends Action {
```suggestion
export interface SetThemesAction extends Action {
```

2021-04-03 07:40 UTC, antonkagakin approved these changes
Лайк, шубшкрибе, колокольчик )

2021-04-03 16:23 UTC, merged