Back 9 api server init postgres
yanprak/yan-run pull request #62
Opened 2021-04-08 16:32 UTC by ferahar

./src/server/server.ts.
Delete "dataGenerator" before releasing the product!

2021-04-08 16:47 UTC, antonkagakin requested changes

2021-04-08 16:47 UTC, antonkagakin commented on package.json
> +    "start:csr-watch": "npm-run-all --print-label --parallel server:dev-csr watch:csr-client",
Надо api-index.js, тобишь отдельный api-server оставить :)

2021-04-08 16:47 UTC, antonkagakin commented on src/server/router/api/forumRoutes.ts
> +          message: 'Message has been successfully updated with like',
```suggestion
          message: 'OK',
```

2021-04-08 16:47 UTC, antonkagakin commented on src/server/api/index.ts
>  const sequelize = new Sequelize(sequelizeOptions);
Чет мне кажется что точки входа, до базы данных должны быть в одном месте, было бы логичней

2021-04-08 19:16 UTC, rade363 commented on src/server/api/models/postgres/Messages.ts
> +  createdAt?: string;
Почему свойства `id`, `reactions` и `createdAt` опциональные?
`id` и `createdAt` всегда есть у любого сообщения, да и reactions тоже - просто изначально там объект с пустыми массивами у свойств.

2021-04-08 19:17 UTC, rade363 commented on src/server/api/models/postgres/Topics.ts
> +  createdAt?: string;
Тот же вопрос )

2021-04-09 09:27 UTC, ferahar commented on src/server/api/models/postgres/Messages.ts
> +  createdAt?: string;
`id` и `createdAt` создаются ORM  иначе придется вручную вставлять так как TS будет ругаться
`reactions` исправлю

2021-04-09 12:18 UTC, antonkagakin approved these changes

2021-04-09 12:18 UTC, antonkagakin commented on src/api-server/router/forumRoutes.ts
> +    const { page } = req.query;
page || 0.
иначе +undefined превратится в NaN

2021-04-09 13:37 UTC, rade363 approved these changes

2021-04-09 13:37 UTC, rade363 commented on api-index.js
> +// }
Подключение к MongoDB перенесено в `src/api-server/server.ts`, наверное закомментированное можно удалять?)

2021-04-09 14:22 UTC, ferahar commented on api-index.js
> +// }
)) удалю

2021-04-09 14:34 UTC, merged