back-10-xss Added helmet and created security.md file
yanprak/yan-run pull request #63
Opened 2021-04-09 19:03 UTC by rade363

Если честно - немного в ступоре от задачи. Попытался проверить проект и описал как смог. 
Правки/предложения приветствуются)

2021-04-12 13:59 UTC, ferahar commented on src/api-server/server.ts
> +  .use(helmet())
так ка юзаем `Helmet` то:
.disabled('x-powered-by') +> app.use(helmet.hidePoweredBy())
если просто use(helmet()) то он это автоматом делает
добавим app.use(helmet.xssFilter())
защита от внешних
use(helmet.contentSecurityPolicy({
        directives: {
          defaultSrc: [
            '\'self\'',
            'https://ya-praktikum.tech',
            ... other path

2021-04-12 13:59 UTC, ferahar commented on src/api-server/server.ts
> +  .use(helmet())
https://expressjs.com/ru/advanced/best-practice-security.html

2021-04-13 03:41 UTC, antonkagakin requested changes

2021-04-13 03:41 UTC, antonkagakin commented on src/api-server/server.ts
> +  .use(helmet())
тут я могу только поддержать, сам не разбирался в вопросе )) но идея либо просто использовать helmet() либо действительно полноценно настроить

2021-04-13 10:04 UTC, rade363 commented on src/api-server/server.ts
> +  .use(helmet())
@ferahar @antonkagakin я на основе этой приведённой статьи и документации и ставил Helmet.

Про `app.disable('x-powered-by');` :
>Если вы используете helmet.js, это будет сделано автоматически.

Окей, могу удалить `disable('x-powered-by');`.

По поводу `app.use(helmet())`, [из документации](https://www.npmjs.com/package/helmet):
```
In other words, these two things are equivalent:
// This...
app.use(helmet());

// ...is equivalent to this:
app.use(helmet.contentSecurityPolicy());
app.use(helmet.dnsPrefetchControl());
app.use(helmet.expectCt());
app.use(helmet.frameguard());
app.use(helmet.hidePoweredBy());
app.use(helmet.hsts());
app.use(helmet.ieNoOpen());
app.use(helmet.noSniff());
app.use(helmet.permittedCrossDomainPolicies());
app.use(helmet.referrerPolicy());
app.use(helmet.xssFilter());

```

Поэтому не стал настраивать `helmet.xssFilter()`.

С настройкой cSP опыта нет, поэтому и стал указывать ничего. 
Моё имхо - дефолтных достаточно, если есть понимание/знания/опыт как настраивать helmet лучше - welcome )

2021-04-15 12:41 UTC, merged