front-45-users-sync-postgres
yanprak/yan-run pull request #64
Opened 2021-04-11 14:08 UTC by ferahar

2021-04-13 14:50 UTC, antonkagakin requested changes
1) То что обговаривали про signin/singup через яндекс и сохранение у нас
2) про theme_id начинающийся с 0ля
3) еще чет по мелочи

2021-04-13 14:50 UTC, antonkagakin commented on src/api-server/api/models/postgres/Themes.ts
> +  style!: string;
чет пришло время убивать код если не нужен ))

2021-04-13 14:50 UTC, antonkagakin commented on src/api-server/api/models/postgres/Users.ts
>      field: 'first_name',
В таких случаях маппинг не нужен, по умолчанию он же как ключ называется в модели - так и в базе будет, то есть можно свернуть до упрощенного задания `@Column(DataType.STRING)`

С полями ниже также

2021-04-13 14:50 UTC, antonkagakin commented on src/api-server/server.ts
> +  // })
Заголовков было больше насолько я помню, и мы же нашли вроде решение чтобы не комментить это всё

2021-04-13 14:50 UTC, antonkagakin commented on src/api-server/utils/dataGenerator/index.ts
> +    .catch(e => console.log(e));
Там оказывается проще, когда sequelize.sync делаешь - передаешь параметром true - и он синкается через дроп старых данных, то есть всегда будет убивать таблицы если они есть - и потом создавать

2021-04-13 14:50 UTC, antonkagakin commented on src/client/API/index.ts
> +
чет странно - эти изменения есть в девелопе а он на дифф показывает

2021-04-13 14:50 UTC, antonkagakin commented on src/client/store/user/thunks.ts
> +  getUserById, updateUser,
каждый элемент на новой строке - ради читаемости

2021-04-13 14:50 UTC, antonkagakin commented on src/client/utils/theme/index.ts
> +export default function changeTheme(theme:UserTheme = dark) {
```suggestion
export default function changeTheme(theme: UserTheme = dark) {
```
eslint
И разве на клиенте у нас должны быть темы? может логичней предзагружать тему из базы?

2021-04-13 14:50 UTC, antonkagakin commented on src/client/store/user/thunks.ts
> +      console.log('Theme => ', r);
signin -> идем в яндекс
  -> получаем добро -> записываем к нам в базу если его там нет -> работа с темами итд
  -> получаем зло -> removeUser

c signup - такая же история

2021-04-13 14:50 UTC, antonkagakin commented on src/client/store/user/thunks.ts
> +    // .then(r => dispatch(setUser(r.data)))
такая же идея, при проверке логина - пытемся проверить пользователя через яндекс, если ок - создаем если нет в базе иначе signout

2021-04-13 14:50 UTC, antonkagakin commented on src/client/store/user/thunks.ts
> +    })
update аватара - так же обновляем в яндексе, обновляем у нас, делаем setUser

2021-04-13 14:50 UTC, antonkagakin commented on src/client/utils/theme/themes/dark.ts
>  };
Опять же, в базе `id` начинаются с 1цы
и на клиенте их быть не должно, либо только 1на - для дефолта, иначе смысл в догружать? или мы по темам храним только `light` `dark`, а они все хранятся на клиенте?

2021-04-14 22:35 UTC, rade363 reviewed
Офигеть конечно объём работы, особенно с User'ом 👍

2021-04-14 22:35 UTC, rade363 commented on src/api-server/api/models/postgres/Users.ts
> +  display_name: Nullable<string>;
Что-то я совсем запутался с `snake_case` и `camelCase` ))
Помню обсуждали, но забыл почему решили снова вернуться к `snake_case`... Обсудим

2021-04-14 22:35 UTC, rade363 commented on src/api-server/api/models/postgres/Users.ts
> +  them!: Themes;
```suggestion
  theme!: Themes;
```

2021-04-14 22:35 UTC, rade363 commented on src/client/pages/profile/Profile.tsx
> +          <h3 className="h3">{`Theme: ${!current ? '' : current.name}`}</h3>
А тут так прокатит или в ошибку вывалится?
```suggestion
          <h3 className="h3">{`Theme: ${current.name || ''}`}</h3>
```

2021-04-14 22:35 UTC, rade363 commented on src/client/store/theme/actions.ts
> +export const SET_REMOVE_THEME = 'SET_REMOVE_THEME';
```suggestion
export const REMOVE_THEME = 'REMOVE_THEME';
```

2021-04-14 22:35 UTC, rade363 commented on src/client/store/theme/types.ts
> +  type: 'SET_REMOVE_THEME';
Минорная вкусновщина, но может 
```suggestion
  type: 'REMOVE_THEME';
```

2021-04-14 22:35 UTC, rade363 commented on src/client/store/theme/types.ts
> +export interface SetRemoveThemeAction extends Action {
Соответственно тут 
```suggestion
export interface RemoveThemeAction extends Action {
```

2021-04-14 22:35 UTC, rade363 commented on src/client/store/user/types.ts
> +export type Fun = <T>(data: T) => Promise<AxiosResponse>;
Хаха почему `Fun`?))
Это в смысле "веселье" или в смысле сокращение от `Function`?

2021-04-14 22:35 UTC, rade363 commented on src/client/store/user/thunks.ts
>  };
Ух сколько всего, мощно 💪

2021-04-15 06:21 UTC, ferahar commented on src/api-server/api/models/postgres/Users.ts
> +  display_name: Nullable<string>;
Пришлось так сделать из-за ПрактикAPI(swagger) Иначе можно еще сильнее запутаться((

2021-04-16 12:32 UTC, merged